name: build docker image
run-name: "build docker image: ${{ github.event.inputs.docker_tag }}"

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        type: string
        description: "tag for the docker image"
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
        path: this
    
    - uses: actions/checkout@v4
      with:
        repository: ytsaurus/ytsaurus
        path: ytsaurus

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push the Docker image
      run: |
        docker build ./ytsaurus --file ./this/Dockerfile \
        --tag ghcr.io/dmi-feo/ytsaurus-python-sdk-tests-runner:${{ github.event.inputs.docker_tag }} \
        --platform linux/amd64 \
        --push
